"""
DDL Generator Service.

Generates DDL scripts for star schema tables (supports SQLite and PostgreSQL).
"""
import pandas as pd
from typing import Dict, List, Any, Optional
from services.star_schema_generator import StarSchema, DimensionTable, FactTable
from config import settings


class DDLGenerator:
    """
    Generates DDL scripts for data warehouse tables.
    Supports both SQLite and PostgreSQL.
    """

    # Detect database type
    is_sqlite = settings.DATABASE_URL.startswith("sqlite")

    # Pandas dtype to SQL type mapping (PostgreSQL)
    DTYPE_MAP_POSTGRES = {
        'int64': 'BIGINT',
        'int32': 'INTEGER',
        'int16': 'SMALLINT',
        'int8': 'SMALLINT',
        'float64': 'DOUBLE PRECISION',
        'float32': 'REAL',
        'bool': 'BOOLEAN',
        'datetime64[ns]': 'TIMESTAMP',
        'datetime64': 'TIMESTAMP',
        'timedelta64[ns]': 'INTERVAL',
        'object': 'VARCHAR(255)',
        'category': 'VARCHAR(255)',
    }

    # Pandas dtype to SQL type mapping (SQLite)
    DTYPE_MAP_SQLITE = {
        'int64': 'INTEGER',
        'int32': 'INTEGER',
        'int16': 'INTEGER',
        'int8': 'INTEGER',
        'float64': 'REAL',
        'float32': 'REAL',
        'bool': 'INTEGER',
        'datetime64[ns]': 'TEXT',
        'datetime64': 'TEXT',
        'timedelta64[ns]': 'TEXT',
        'object': 'TEXT',
        'category': 'TEXT',
    }

    def __init__(self, star_schema: StarSchema):
        """
        Initialize DDL generator.

        Args:
            star_schema: StarSchema object to generate DDL for
        """
        self.star_schema = star_schema

    @property
    def dtype_map(self):
        """Get appropriate dtype map based on database."""
        return self.DTYPE_MAP_SQLITE if self.is_sqlite else self.DTYPE_MAP_POSTGRES

    def generate_all(self) -> str:
        """
        Generate complete DDL script for all tables.

        Returns:
            SQL DDL script as string
        """
        ddl_parts = []

        # Header comment
        ddl_parts.append(self._generate_header())

        # Drop existing tables (in reverse order due to FK constraints)
        ddl_parts.append(self._generate_drop_statements())

        # Create dimension tables first
        for dim in self.star_schema.dimensions:
            ddl_parts.append(self._generate_dimension_ddl(dim))

        # Create fact table
        ddl_parts.append(self._generate_fact_ddl())

        # Create indexes (skip for SQLite in initial load - can be added later)
        if not self.is_sqlite:
            ddl_parts.append(self._generate_indexes())

        return '\n\n'.join(ddl_parts)

    def _generate_header(self) -> str:
        """Generate DDL header comment."""
        db_type = "SQLite" if self.is_sqlite else "PostgreSQL"
        return f"""-- ============================================
-- Star Schema DDL ({db_type})
-- Generated by BI Platform
-- ============================================
"""

    def _generate_drop_statements(self) -> str:
        """Generate DROP TABLE statements."""
        statements = ["-- Drop existing tables (if any)"]

        # SQLite doesn't support CASCADE
        cascade = "" if self.is_sqlite else " CASCADE"

        # Drop fact table first (has FK references)
        statements.append(f"DROP TABLE IF EXISTS {self.star_schema.fact_table.name}{cascade};")

        # Then drop dimension tables
        for dim in self.star_schema.dimensions:
            statements.append(f"DROP TABLE IF EXISTS {dim.name}{cascade};")

        return '\n'.join(statements)

    def _generate_dimension_ddl(self, dim: DimensionTable) -> str:
        """
        Generate CREATE TABLE statement for a dimension.

        Args:
            dim: DimensionTable object

        Returns:
            SQL CREATE TABLE statement
        """
        lines = [f"-- Dimension: {dim.display_name}"]
        lines.append(f"CREATE TABLE IF NOT EXISTS {dim.name} (")

        columns = []

        # Surrogate key (primary key) - different syntax for SQLite vs PostgreSQL
        if self.is_sqlite:
            columns.append(f"    {dim.surrogate_key} INTEGER PRIMARY KEY AUTOINCREMENT")
        else:
            columns.append(f"    {dim.surrogate_key} SERIAL PRIMARY KEY")

        # Add columns from DataFrame
        if dim.dataframe is not None:
            for col in dim.dataframe.columns:
                if col == dim.surrogate_key:
                    continue  # Skip surrogate key (already added)

                dtype = str(dim.dataframe[col].dtype)
                sql_type = self._get_sql_type(dtype, dim.dataframe[col])

                # Check if nullable
                nullable = dim.dataframe[col].isna().any()
                null_clause = "" if nullable else " NOT NULL"

                columns.append(f"    {col} {sql_type}{null_clause}")

        # Add metadata columns
        if self.is_sqlite:
            columns.append("    created_at TEXT DEFAULT (datetime('now'))")
            columns.append("    updated_at TEXT DEFAULT (datetime('now'))")
        else:
            columns.append("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
            columns.append("    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")

        lines.append(',\n'.join(columns))
        lines.append(");")

        # Add unique constraint on natural key if exists (only for PostgreSQL)
        if not self.is_sqlite:
            if dim.natural_key and dim.natural_key in (dim.dataframe.columns if dim.dataframe is not None else []):
                lines.append(f"\n-- Natural key constraint")
                lines.append(f"ALTER TABLE {dim.name} ADD CONSTRAINT uq_{dim.name}_{dim.natural_key} UNIQUE ({dim.natural_key});")

        return '\n'.join(lines)

    def _generate_fact_ddl(self) -> str:
        """
        Generate CREATE TABLE statement for fact table.

        Returns:
            SQL CREATE TABLE statement
        """
        fact = self.star_schema.fact_table

        lines = [f"-- Fact Table: {fact.display_name}"]
        lines.append(f"CREATE TABLE IF NOT EXISTS {fact.name} (")

        columns = []

        # Surrogate key - different syntax for SQLite vs PostgreSQL
        if self.is_sqlite:
            columns.append("    sk_fact INTEGER PRIMARY KEY AUTOINCREMENT")
        else:
            columns.append("    sk_fact SERIAL PRIMARY KEY")

        # Add foreign key columns for dimensions
        for dim in self.star_schema.dimensions:
            fk_col = f"fk_{dim.name}"
            if self.is_sqlite:
                # SQLite: simpler FK syntax
                columns.append(f"    {fk_col} INTEGER")
            else:
                columns.append(f"    {fk_col} INTEGER REFERENCES {dim.name}({dim.surrogate_key})")

        # Add measure columns from DataFrame
        if fact.dataframe is not None:
            for col in fact.dataframe.columns:
                if col == 'sk_fact' or col.startswith('fk_'):
                    continue  # Skip key columns (already added)

                dtype = str(fact.dataframe[col].dtype)
                sql_type = self._get_sql_type(dtype, fact.dataframe[col], is_measure=True)

                columns.append(f"    {col} {sql_type}")

        # Add metadata columns
        if self.is_sqlite:
            columns.append("    created_at TEXT DEFAULT (datetime('now'))")
        else:
            columns.append("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")

        lines.append(',\n'.join(columns))
        lines.append(");")

        return '\n'.join(lines)

    def _generate_indexes(self) -> str:
        """
        Generate CREATE INDEX statements for analytics optimization.

        Returns:
            SQL CREATE INDEX statements
        """
        lines = ["-- Indexes for analytics optimization"]

        # Indexes on dimension natural keys
        for dim in self.star_schema.dimensions:
            if dim.natural_key:
                lines.append(
                    f"CREATE INDEX IF NOT EXISTS idx_{dim.name}_{dim.natural_key} "
                    f"ON {dim.name} ({dim.natural_key});"
                )

            # Index on time dimension date columns
            if dim.is_time_dimension:
                lines.append(
                    f"CREATE INDEX IF NOT EXISTS idx_{dim.name}_full_date "
                    f"ON {dim.name} (full_date);"
                )
                lines.append(
                    f"CREATE INDEX IF NOT EXISTS idx_{dim.name}_year_month "
                    f"ON {dim.name} (year, month);"
                )

        # Indexes on fact table foreign keys
        for dim in self.star_schema.dimensions:
            fk_col = f"fk_{dim.name}"
            lines.append(
                f"CREATE INDEX IF NOT EXISTS idx_{self.star_schema.fact_table.name}_{fk_col} "
                f"ON {self.star_schema.fact_table.name} ({fk_col});"
            )

        # Composite index on all dimension FKs (for common aggregations)
        if len(self.star_schema.dimensions) <= 5:
            fk_cols = [f"fk_{dim.name}" for dim in self.star_schema.dimensions]
            lines.append(
                f"CREATE INDEX IF NOT EXISTS idx_{self.star_schema.fact_table.name}_dims "
                f"ON {self.star_schema.fact_table.name} ({', '.join(fk_cols)});"
            )

        return '\n'.join(lines)

    def _get_sql_type(
            self,
            pandas_dtype: str,
            series: pd.Series,
            is_measure: bool = False
    ) -> str:
        """
        Map pandas dtype to SQL type.

        Args:
            pandas_dtype: Pandas dtype string
            series: The actual series (for length estimation)
            is_measure: Whether this is a measure column

        Returns:
            SQL type string
        """
        # Direct mapping
        if pandas_dtype in self.dtype_map:
            return self.dtype_map[pandas_dtype]

        # Handle specific patterns
        if self.is_sqlite:
            if 'int' in pandas_dtype.lower():
                return 'INTEGER'
            if 'float' in pandas_dtype.lower():
                return 'REAL'
            if 'bool' in pandas_dtype.lower():
                return 'INTEGER'
            if 'datetime' in pandas_dtype.lower() or 'date' in pandas_dtype.lower():
                return 'TEXT'
            return 'TEXT'
        else:
            # PostgreSQL
            if 'int' in pandas_dtype.lower():
                return 'BIGINT'
            if 'float' in pandas_dtype.lower():
                return 'DOUBLE PRECISION' if is_measure else 'REAL'
            if 'bool' in pandas_dtype.lower():
                return 'BOOLEAN'
            if 'datetime' in pandas_dtype.lower():
                return 'TIMESTAMP'
            if 'date' in pandas_dtype.lower():
                return 'DATE'

            # For object types, estimate VARCHAR length
            if pandas_dtype == 'object':
                max_len = series.astype(str).str.len().max()
                if pd.isna(max_len):
                    max_len = 255

                if max_len <= 50:
                    return 'VARCHAR(50)'
                elif max_len <= 100:
                    return 'VARCHAR(100)'
                elif max_len <= 255:
                    return 'VARCHAR(255)'
                elif max_len <= 1000:
                    return 'VARCHAR(1000)'
                else:
                    return 'TEXT'

            # Default
            return 'VARCHAR(255)'

    def generate_dimension_ddl_only(self, dim_name: str) -> Optional[str]:
        """Generate DDL for a specific dimension."""
        for dim in self.star_schema.dimensions:
            if dim.name == dim_name:
                return self._generate_dimension_ddl(dim)
        return None

    def generate_fact_ddl_only(self) -> str:
        """Generate DDL for fact table only."""
        return self._generate_fact_ddl()

    def get_table_definitions(self) -> Dict[str, Dict[str, Any]]:
        """
        Get table definitions as dictionary.

        Returns:
            Dictionary with table definitions
        """
        tables = {}

        # Dimensions
        for dim in self.star_schema.dimensions:
            columns = []
            if dim.dataframe is not None:
                for col in dim.dataframe.columns:
                    dtype = str(dim.dataframe[col].dtype)
                    columns.append({
                        'name': col,
                        'type': self._get_sql_type(dtype, dim.dataframe[col]),
                        'is_primary_key': col == dim.surrogate_key,
                        'is_natural_key': col == dim.natural_key
                    })

            tables[dim.name] = {
                'type': 'dimension',
                'display_name': dim.display_name,
                'columns': columns,
                'primary_key': dim.surrogate_key,
                'natural_key': dim.natural_key,
                'is_time_dimension': dim.is_time_dimension
            }

        # Fact table
        fact = self.star_schema.fact_table
        columns = []
        if fact.dataframe is not None:
            for col in fact.dataframe.columns:
                dtype = str(fact.dataframe[col].dtype)
                columns.append({
                    'name': col,
                    'type': self._get_sql_type(dtype, fact.dataframe[col], is_measure=col in fact.measures),
                    'is_primary_key': col == 'sk_fact',
                    'is_foreign_key': col.startswith('fk_'),
                    'is_measure': col in fact.measures
                })

        tables[fact.name] = {
            'type': 'fact',
            'display_name': fact.display_name,
            'columns': columns,
            'primary_key': 'sk_fact',
            'measures': fact.measures,
            'dimension_keys': fact.dimension_keys
        }

        return tables


def generate_ddl(star_schema: StarSchema) -> str:
    """
    Convenience function to generate DDL.

    Args:
        star_schema: StarSchema object

    Returns:
        DDL script string
    """
    generator = DDLGenerator(star_schema)
    return generator.generate_all()
