"""
Data Cleaning Rules Agent (Layer 2, Agent 2)
=============================================
Generates and applies data cleaning rules using LLM reasoning with
structured Pydantic output and confidence-gated routing.

Reference: [Annam 2025] — "LLMs can automatically propose cleansing
rules by analyzing data samples and metadata."
"""

from __future__ import annotations

import json
import logging
from typing import Any, Literal

import httpx
import numpy as np
import pandas as pd
from pydantic import BaseModel, Field

from services.etl_llm.profiling.schema_profiler import SchemaContext

logger = logging.getLogger(__name__)

CONFIDENCE_THRESHOLD = 0.75


# ── Pydantic models ─────────────────────────────────────────────


class CleaningRule(BaseModel):
    """A single data cleaning rule generated by the LLM."""

    column: str
    rule_type: Literal[
        "fill_null",
        "standardize_format",
        "remove_duplicates",
        "type_cast",
        "clip_outliers",
        "normalize_text",
        "drop_column",
    ]
    params: dict = Field(default_factory=dict)
    priority: int = Field(ge=1, le=3)  # 1=critical, 2=important, 3=optional
    justification: str = ""


class CleaningPlan(BaseModel):
    """Complete cleaning plan generated by the Cleaning Rules Agent."""

    rules: list[CleaningRule]
    estimated_quality_improvement: float = Field(ge=0.0, le=1.0)
    confidence: float = Field(ge=0.0, le=1.0)
    model_used: str = ""


# ── Agent ────────────────────────────────────────────────────────


class CleaningRulesAgent:
    """Cleaning Rules Agent — Agent 2 of the LLM pipeline.

    Uses the same confidence-gated routing as SchemaMappingAgent.

    Reference: [Annam 2025] — LLMs propose cleansing rules from metadata.
    """

    def __init__(
        self,
        ollama_url: str = "http://localhost:11434",
        anthropic_key: str | None = None,
    ) -> None:
        self._ollama_url = ollama_url.rstrip("/")
        self._anthropic_key = anthropic_key

    def _build_prompt(self, schema: SchemaContext) -> str:
        cols_text = "\n".join(
            f"  - {c.name}: dtype={c.dtype}, null%={c.null_pct}, "
            f"unique={c.unique_count}, samples={c.samples[:3]}"
            for c in schema.columns
        )
        return f"""You are an expert data engineer specializing in data quality.

Analyze the following schema and generate cleaning rules:
{cols_text}

For each column, think step by step:
1) Check null rate — if > 5%, suggest fill_null
2) Check format consistency — if text, suggest normalize_text or standardize_format
3) Check for outliers in numeric columns — suggest clip_outliers if needed
4) Check cardinality — if too low, might be worth dropping

Respond ONLY with valid JSON:
{{
  "rules": [
    {{
      "column": "col_name",
      "rule_type": "fill_null|standardize_format|remove_duplicates|type_cast|clip_outliers|normalize_text|drop_column",
      "params": {{}},
      "priority": 1,
      "justification": "reason"
    }}
  ],
  "estimated_quality_improvement": 0.0,
  "confidence": 0.0
}}"""

    def _call_llama(self, prompt: str) -> tuple[dict, float]:
        response = httpx.post(
            f"{self._ollama_url}/api/generate",
            json={"model": "llama3:8b", "prompt": prompt, "format": "json", "stream": False},
            timeout=120,
        )
        response.raise_for_status()
        parsed = json.loads(response.json().get("response", "{}"))
        return parsed, float(parsed.get("confidence", 0.5))

    def _call_claude(self, prompt: str) -> tuple[dict, float]:
        import anthropic

        client = anthropic.Anthropic(api_key=self._anthropic_key)
        msg = client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}],
        )
        text = msg.content[0].text
        start, end = text.find("{"), text.rfind("}") + 1
        if start >= 0 and end > start:
            text = text[start:end]
        return json.loads(text), 0.95

    def generate_cleaning_plan(self, schema: SchemaContext) -> CleaningPlan:
        """Generate a cleaning plan with confidence-gated routing."""
        prompt = self._build_prompt(schema)

        model_used = "llama3:8b"
        try:
            parsed, confidence = self._call_llama(prompt)
            if confidence < CONFIDENCE_THRESHOLD:
                raise ValueError("Low confidence")
        except Exception:
            if self._anthropic_key:
                parsed, confidence = self._call_claude(prompt)
                model_used = "claude-3-5-sonnet"
            else:
                raise

        rules = [
            CleaningRule(**r) for r in parsed.get("rules", [])
        ]
        return CleaningPlan(
            rules=rules,
            estimated_quality_improvement=float(parsed.get("estimated_quality_improvement", 0.1)),
            confidence=confidence,
            model_used=model_used,
        )

    # ── rule application ─────────────────────────────────────────

    def apply_cleaning_plan(
        self, df: pd.DataFrame, plan: CleaningPlan
    ) -> tuple[pd.DataFrame, dict[str, Any]]:
        """Apply each cleaning rule to *df* and return (cleaned_df, report).

        The report tracks rows affected per rule.
        """
        df = df.copy()
        report: dict[str, Any] = {"rules_applied": [], "total_rows_affected": 0}

        for rule in sorted(plan.rules, key=lambda r: r.priority):
            if rule.column not in df.columns and rule.rule_type != "remove_duplicates":
                continue

            rows_before = len(df)
            affected = 0

            if rule.rule_type == "fill_null":
                affected = int(df[rule.column].isna().sum())
                method = rule.params.get("method", "median")
                if method == "median" and pd.api.types.is_numeric_dtype(df[rule.column]):
                    df[rule.column] = df[rule.column].fillna(df[rule.column].median())
                elif method == "mean" and pd.api.types.is_numeric_dtype(df[rule.column]):
                    df[rule.column] = df[rule.column].fillna(df[rule.column].mean())
                elif method == "mode":
                    mode_val = df[rule.column].mode()
                    if len(mode_val) > 0:
                        df[rule.column] = df[rule.column].fillna(mode_val.iloc[0])
                else:
                    constant = rule.params.get("value", "")
                    df[rule.column] = df[rule.column].fillna(constant)

            elif rule.rule_type == "standardize_format":
                fmt = rule.params.get("format", "%Y-%m-%d")
                try:
                    df[rule.column] = pd.to_datetime(df[rule.column]).dt.strftime(fmt)
                    affected = rows_before
                except Exception:
                    pass

            elif rule.rule_type == "remove_duplicates":
                subset = [rule.column] if rule.column in df.columns else None
                df = df.drop_duplicates(subset=subset)
                affected = rows_before - len(df)

            elif rule.rule_type == "type_cast":
                dtype = rule.params.get("dtype", "str")
                try:
                    df[rule.column] = df[rule.column].astype(dtype)
                    affected = rows_before
                except Exception:
                    pass

            elif rule.rule_type == "clip_outliers":
                if pd.api.types.is_numeric_dtype(df[rule.column]):
                    q1 = df[rule.column].quantile(0.25)
                    q3 = df[rule.column].quantile(0.75)
                    iqr = q3 - q1
                    lower = q1 - 1.5 * iqr
                    upper = q3 + 1.5 * iqr
                    before_clip = df[rule.column].copy()
                    df[rule.column] = df[rule.column].clip(lower=lower, upper=upper)
                    affected = int((before_clip != df[rule.column]).sum())

            elif rule.rule_type == "normalize_text":
                if df[rule.column].dtype == object or str(df[rule.column].dtype).startswith("str"):
                    before = df[rule.column].copy()
                    df[rule.column] = df[rule.column].astype(str).str.strip().str.lower()
                    affected = int((before != df[rule.column]).sum())

            elif rule.rule_type == "drop_column":
                df = df.drop(columns=[rule.column])
                affected = rows_before

            report["rules_applied"].append(
                {"rule": rule.rule_type, "column": rule.column, "rows_affected": affected}
            )
            report["total_rows_affected"] += affected

        return df, report
